/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
	"fmt"
	"time"
)

// DashboardSearchSummaryDefinition Dashboard search definition.
type DashboardSearchSummaryDefinition struct {
	Author *Creator `json:"author,omitempty"`
	// Date of creation of the dashboard.
	Created *time.Time `json:"created,omitempty"`
	// URL to the icon of the dashboard.
	Icon *string `json:"icon,omitempty"`
	// ID of the dashboard.
	Id *string `json:"id,omitempty"`
	// Whether or not the dashboard is in the favorites.
	IsFavorite *bool `json:"is_favorite,omitempty"`
	// Whether or not the dashboard is read only.
	IsReadOnly *bool `json:"is_read_only,omitempty"`
	// Whether the dashboard is publicly shared or not.
	IsShared *bool `json:"is_shared,omitempty"`
	// Date of last edition of the dashboard.
	Modified *time.Time `json:"modified,omitempty"`
	// Popularity of the dashboard.
	Popularity *int32 `json:"popularity,omitempty"`
	// Title of the dashboard.
	Title *string       `json:"title,omitempty"`
	Type  DashboardType `json:"type"`
	// URL path to the dashboard.
	Url *string `json:"url,omitempty"`
	// UnparsedObject contains the raw value of the object if there was an error when deserializing into the struct
	UnparsedObject map[string]interface{} `json:-`
}

// NewDashboardSearchSummaryDefinition instantiates a new DashboardSearchSummaryDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardSearchSummaryDefinition(type_ DashboardType) *DashboardSearchSummaryDefinition {
	this := DashboardSearchSummaryDefinition{}
	this.Type = type_
	return &this
}

// NewDashboardSearchSummaryDefinitionWithDefaults instantiates a new DashboardSearchSummaryDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardSearchSummaryDefinitionWithDefaults() *DashboardSearchSummaryDefinition {
	this := DashboardSearchSummaryDefinition{}
	return &this
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetAuthor() Creator {
	if o == nil || o.Author == nil {
		var ret Creator
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetAuthorOk() (*Creator, bool) {
	if o == nil || o.Author == nil {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasAuthor() bool {
	if o != nil && o.Author != nil {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given Creator and assigns it to the Author field.
func (o *DashboardSearchSummaryDefinition) SetAuthor(v Creator) {
	o.Author = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetCreated() time.Time {
	if o == nil || o.Created == nil {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetCreatedOk() (*time.Time, bool) {
	if o == nil || o.Created == nil {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasCreated() bool {
	if o != nil && o.Created != nil {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *DashboardSearchSummaryDefinition) SetCreated(v time.Time) {
	o.Created = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetIcon() string {
	if o == nil || o.Icon == nil {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetIconOk() (*string, bool) {
	if o == nil || o.Icon == nil {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasIcon() bool {
	if o != nil && o.Icon != nil {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *DashboardSearchSummaryDefinition) SetIcon(v string) {
	o.Icon = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DashboardSearchSummaryDefinition) SetId(v string) {
	o.Id = &v
}

// GetIsFavorite returns the IsFavorite field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetIsFavorite() bool {
	if o == nil || o.IsFavorite == nil {
		var ret bool
		return ret
	}
	return *o.IsFavorite
}

// GetIsFavoriteOk returns a tuple with the IsFavorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetIsFavoriteOk() (*bool, bool) {
	if o == nil || o.IsFavorite == nil {
		return nil, false
	}
	return o.IsFavorite, true
}

// HasIsFavorite returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasIsFavorite() bool {
	if o != nil && o.IsFavorite != nil {
		return true
	}

	return false
}

// SetIsFavorite gets a reference to the given bool and assigns it to the IsFavorite field.
func (o *DashboardSearchSummaryDefinition) SetIsFavorite(v bool) {
	o.IsFavorite = &v
}

// GetIsReadOnly returns the IsReadOnly field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetIsReadOnly() bool {
	if o == nil || o.IsReadOnly == nil {
		var ret bool
		return ret
	}
	return *o.IsReadOnly
}

// GetIsReadOnlyOk returns a tuple with the IsReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetIsReadOnlyOk() (*bool, bool) {
	if o == nil || o.IsReadOnly == nil {
		return nil, false
	}
	return o.IsReadOnly, true
}

// HasIsReadOnly returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasIsReadOnly() bool {
	if o != nil && o.IsReadOnly != nil {
		return true
	}

	return false
}

// SetIsReadOnly gets a reference to the given bool and assigns it to the IsReadOnly field.
func (o *DashboardSearchSummaryDefinition) SetIsReadOnly(v bool) {
	o.IsReadOnly = &v
}

// GetIsShared returns the IsShared field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetIsShared() bool {
	if o == nil || o.IsShared == nil {
		var ret bool
		return ret
	}
	return *o.IsShared
}

// GetIsSharedOk returns a tuple with the IsShared field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetIsSharedOk() (*bool, bool) {
	if o == nil || o.IsShared == nil {
		return nil, false
	}
	return o.IsShared, true
}

// HasIsShared returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasIsShared() bool {
	if o != nil && o.IsShared != nil {
		return true
	}

	return false
}

// SetIsShared gets a reference to the given bool and assigns it to the IsShared field.
func (o *DashboardSearchSummaryDefinition) SetIsShared(v bool) {
	o.IsShared = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetModified() time.Time {
	if o == nil || o.Modified == nil {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetModifiedOk() (*time.Time, bool) {
	if o == nil || o.Modified == nil {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasModified() bool {
	if o != nil && o.Modified != nil {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *DashboardSearchSummaryDefinition) SetModified(v time.Time) {
	o.Modified = &v
}

// GetPopularity returns the Popularity field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetPopularity() int32 {
	if o == nil || o.Popularity == nil {
		var ret int32
		return ret
	}
	return *o.Popularity
}

// GetPopularityOk returns a tuple with the Popularity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetPopularityOk() (*int32, bool) {
	if o == nil || o.Popularity == nil {
		return nil, false
	}
	return o.Popularity, true
}

// HasPopularity returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasPopularity() bool {
	if o != nil && o.Popularity != nil {
		return true
	}

	return false
}

// SetPopularity gets a reference to the given int32 and assigns it to the Popularity field.
func (o *DashboardSearchSummaryDefinition) SetPopularity(v int32) {
	o.Popularity = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *DashboardSearchSummaryDefinition) SetTitle(v string) {
	o.Title = &v
}

// GetType returns the Type field value
func (o *DashboardSearchSummaryDefinition) GetType() DashboardType {
	if o == nil {
		var ret DashboardType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetTypeOk() (*DashboardType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DashboardSearchSummaryDefinition) SetType(v DashboardType) {
	o.Type = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *DashboardSearchSummaryDefinition) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardSearchSummaryDefinition) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *DashboardSearchSummaryDefinition) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *DashboardSearchSummaryDefinition) SetUrl(v string) {
	o.Url = &v
}

func (o DashboardSearchSummaryDefinition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UnparsedObject != nil {
		return json.Marshal(o.UnparsedObject)
	}
	if o.Author != nil {
		toSerialize["author"] = o.Author
	}
	if o.Created != nil {
		toSerialize["created"] = o.Created
	}
	if o.Icon != nil {
		toSerialize["icon"] = o.Icon
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.IsFavorite != nil {
		toSerialize["is_favorite"] = o.IsFavorite
	}
	if o.IsReadOnly != nil {
		toSerialize["is_read_only"] = o.IsReadOnly
	}
	if o.IsShared != nil {
		toSerialize["is_shared"] = o.IsShared
	}
	if o.Modified != nil {
		toSerialize["modified"] = o.Modified
	}
	if o.Popularity != nil {
		toSerialize["popularity"] = o.Popularity
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

func (o *DashboardSearchSummaryDefinition) UnmarshalJSON(bytes []byte) (err error) {
	raw := map[string]interface{}{}
	required := struct {
		Type *DashboardType `json:"type"`
	}{}
	all := struct {
		Author     *Creator      `json:"author,omitempty"`
		Created    *time.Time    `json:"created,omitempty"`
		Icon       *string       `json:"icon,omitempty"`
		Id         *string       `json:"id,omitempty"`
		IsFavorite *bool         `json:"is_favorite,omitempty"`
		IsReadOnly *bool         `json:"is_read_only,omitempty"`
		IsShared   *bool         `json:"is_shared,omitempty"`
		Modified   *time.Time    `json:"modified,omitempty"`
		Popularity *int32        `json:"popularity,omitempty"`
		Title      *string       `json:"title,omitempty"`
		Type       DashboardType `json:"type"`
		Url        *string       `json:"url,omitempty"`
	}{}
	err = json.Unmarshal(bytes, &required)
	if err != nil {
		return err
	}
	if required.Type == nil {
		return fmt.Errorf("Required field type missing")
	}
	err = json.Unmarshal(bytes, &all)
	if err != nil {
		err = json.Unmarshal(bytes, &raw)
		if err != nil {
			return err
		}
		o.UnparsedObject = raw
		return nil
	}
	if v := all.Type; !v.IsValid() {
		err = json.Unmarshal(bytes, &raw)
		if err != nil {
			return err
		}
		o.UnparsedObject = raw
		return nil
	}
	o.Author = all.Author
	o.Created = all.Created
	o.Icon = all.Icon
	o.Id = all.Id
	o.IsFavorite = all.IsFavorite
	o.IsReadOnly = all.IsReadOnly
	o.IsShared = all.IsShared
	o.Modified = all.Modified
	o.Popularity = all.Popularity
	o.Title = all.Title
	o.Type = all.Type
	o.Url = all.Url
	return nil
}

type NullableDashboardSearchSummaryDefinition struct {
	value *DashboardSearchSummaryDefinition
	isSet bool
}

func (v NullableDashboardSearchSummaryDefinition) Get() *DashboardSearchSummaryDefinition {
	return v.value
}

func (v *NullableDashboardSearchSummaryDefinition) Set(val *DashboardSearchSummaryDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardSearchSummaryDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardSearchSummaryDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardSearchSummaryDefinition(val *DashboardSearchSummaryDefinition) *NullableDashboardSearchSummaryDefinition {
	return &NullableDashboardSearchSummaryDefinition{value: val, isSet: true}
}

func (v NullableDashboardSearchSummaryDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardSearchSummaryDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
